/*
 * File: js/app/view/ui/CommentsPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.ui.CommentsPanel', {
    extend: 'Ext.panel.Panel',
    requires: [
        'BlogApp.view.CommentsList',
        'BlogApp.view.CommentForm'
    ],

    height: 300,
    id: '',
    maxHeight: 500,
    autoScroll: true,
    title: 'Comments',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'commentslist',
                    padding: 10
                },
                {
                    xtype: 'commentform'
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    tooltip: 'Manage comments',
                    type: 'gear',
                    hidden: 'true'
                }
            ]
        });

        me.callParent(arguments);
    }

});