Ext.define('Bancha.REMOTE_API',{
  "url":"\/bancha-dispatcher.php",
  "namespace":"Bancha.RemoteStubs",
  "type":"remoting",
  "metadata":{
    "Article":{
      "idProperty":"id",
      "displayField":"title",
      "fields":[
        {
          "name":"id",
          "allowNull":false,
          "defaultValue":"",
          "type":"int"
        },
        {
          "name":"title",
          "allowNull":true,
          "defaultValue":null,
          "type":"string"
        },
        {
          "name":"date",
          "allowNull":true,
          "defaultValue":null,
          "type":"date",
          "dateFormat":"Y-m-d H:i:s"
        },
        {
          "name":"body",
          "allowNull":true,
          "defaultValue":null,
          "type":"string"
        },
        {
          "name":"published",
          "allowNull":true,
          "defaultValue":"0",
          "type":"boolean"
        },
        {
          "name":"user_id",
          "allowNull":false,
          "defaultValue":"",
          "type":"int"
        }
      ],
      "validations":[
        {
          "type":"inclusion",
          "field":"published",
          "list":[
            true,
            false,
            "0",
            "1",
            0,
            1
          ]
        },
        {
          "type":"range",
          "field":"user_id"
        }
      ],
      "associations":[
        {
          "type":"belongsTo",
          "model":"Bancha.model.User",
          "foreignKey":"user_id",
          "getterName":"getUser",
          "setterName":"setUser",
          "name":"user"
        },
        {
          "type":"hasMany",
          "model":"Bancha.model.Comment",
          "foreignKey":"article_id",
          "getterName":"comments",
          "setterName":"setComments",
          "name":"comments"
        }
      ],
      "sorters":[
        
      ]
    },
    "Comment":{
      "idProperty":"id",
      "displayField":"comment",
      "fields":[
        {
          "name":"id",
          "allowNull":false,
          "defaultValue":"",
          "type":"int"
        },
        {
          "name":"article_id",
          "allowNull":false,
          "defaultValue":"",
          "type":"int"
        },
        {
          "name":"user_id",
          "allowNull":false,
          "defaultValue":"",
          "type":"int"
        },
        {
          "name":"comment",
          "allowNull":false,
          "defaultValue":"",
          "type":"string"
        },
        {
          "name":"created",
          "allowNull":true,
          "defaultValue":null,
          "type":"date",
          "dateFormat":"Y-m-d H:i:s"
        }
      ],
      "validations":[
        {
          "type":"range",
          "field":"article_id"
        }
      ],
      "associations":[
        {
          "type":"belongsTo",
          "model":"Bancha.model.Article",
          "foreignKey":"article_id",
          "getterName":"getArticle",
          "setterName":"setArticle",
          "name":"article"
        }
      ],
      "sorters":[
        
      ]
    },
    "User":{
      "idProperty":"id",
      "displayField":"name",
      "fields":[
        {
          "name":"id",
          "allowNull":false,
          "defaultValue":"",
          "type":"int"
        },
        {
          "name":"username",
          "allowNull":false,
          "defaultValue":"",
          "type":"string"
        },
        {
          "name":"password",
          "allowNull":false,
          "defaultValue":"",
          "type":"string"
        },
        {
          "name":"name",
          "allowNull":true,
          "defaultValue":null,
          "type":"string"
        },
        {
          "name":"role",
          "allowNull":false,
          "defaultValue":"user",
          "type":"string"
        },
        {
          "name":"created",
          "allowNull":true,
          "defaultValue":null,
          "type":"date",
          "dateFormat":"Y-m-d H:i:s"
        },
        {
          "name":"modified",
          "allowNull":true,
          "defaultValue":null,
          "type":"date",
          "dateFormat":"Y-m-d H:i:s"
        },
        {
          "name":"email",
          "allowNull":true,
          "defaultValue":null,
          "type":"string"
        }
      ],
      "validations":[
        {
          "type":"range",
          "field":"id",
          "precision":0
        },
        {
          "type":"length",
          "field":"name",
          "min":3,
          "max":64
        },
        {
          "type":"presence",
          "field":"username"
        },
        {
          "type":"length",
          "field":"username",
          "min":3,
          "max":64
        },
        {
          "type":"format",
          "field":"username",
          "matcher":"banchaAlphanum"
        },
        {
          "type":"presence",
          "field":"email"
        },
        {
          "type":"format",
          "field":"email",
          "matcher":"banchaEmail"
        }
      ],
      "associations":[
        {
          "type":"hasMany",
          "model":"Bancha.model.Article",
          "foreignKey":"user_id",
          "getterName":"articles",
          "setterName":"setArticles",
          "name":"articles"
        }
      ],
      "sorters":[
        
      ]
    },
    "_UID":"54374f8d5d63d343852608",
    "_ServerDebugLevel":2,
    "_ServerError":false
  },
  "actions":{
    "Article":[
      {
        "name":"getAll",
        "len":0
      },
      {
        "name":"read",
        "len":1
      },
      {
        "name":"create",
        "len":1
      },
      {
        "name":"update",
        "len":1
      },
      {
        "name":"destroy",
        "len":1
      },
      {
        "name":"submit",
        "len":1,
        "formHandler":true
      }
    ],
    "Comment":[
      {
        "name":"getAll",
        "len":0
      },
      {
        "name":"read",
        "len":1
      },
      {
        "name":"create",
        "len":1
      },
      {
        "name":"update",
        "len":1
      },
      {
        "name":"destroy",
        "len":1
      },
      {
        "name":"submit",
        "len":1,
        "formHandler":true
      }
    ],
    "User":[
      {
        "name":"getAll",
        "len":0
      },
      {
        "name":"read",
        "len":1
      },
      {
        "name":"create",
        "len":1
      },
      {
        "name":"update",
        "len":1
      },
      {
        "name":"destroy",
        "len":1
      },
      {
        "name":"submit",
        "len":1,
        "formHandler":true
      },
      {
        "name":"login",
        "len":1
      },
      {
        "name":"logout",
        "len":0
      }
    ],
    "Bancha":[
      {
        "name":"loadMetaData",
        "len":1
      },
      {
        "name":"logError",
        "len":2
      }
    ]
  },
  "singleton":true
});

Ext.define('Bancha.model.Article', {
    extend: 'Bancha.data.Model'
});
Ext.define('Bancha.model.Comment', {
    extend: 'Bancha.data.Model'
});
Ext.define('Bancha.model.User', {
    extend: 'Bancha.data.Model'
});
