/*
 * File: app/controller/Authentification.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.controller.Authentification', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'viewport',
            selector: 'viewport'
        },
        {
            ref: 'loginWindow',
            selector: 'loginwindow'
        },
        {
            ref: 'loginForm',
            selector: 'loginwindow formpanel'
        }
    ],

    onLoginClick: function(button, e, eOpts) {
        // log the user in
        var me = this, // keep reference to controller and window through scope
        win = this.getLoginWindow(), 
        values = win.down('form').getValues();

        // mask while asking the server
        win.setLoading('logging in...');

        // login through the banchaRemotable method UsersController->login
        Bancha.getStub('User').login(values, {
            success: function(result, response) {
                if(result.success) {
                    // we are logged in, so hide login window
                    win.hide();

                    // tell application about login
                    var user = Ext.create('BlogApp.model.User', result.data);
                    me.application.fireEvent('loggedin', user);
                } else {
                    // error handling
                    Ext.Msg.alert('Login Failed!', 'Username and password don\'t match!');
                    win.setLoading(false);
                }
            },
            failure: function(result, response) {
                Ext.Msg.alert('Warning!', 'Authentication server is unreachable or returned with an error');
                win.setLoading(false);
            }
        });
    },

    onLoginEnter: function(textfield, e, eOpts) {
        if(e.keyCode === 13) { // is enter key
            this.onLoginClick();
        }
    },

    onLogoutClick: function(tool, e, eOpts) {

        // mask for user
        this.getViewport().setLoading('Logging out...');

        // logout
        Bancha.getStub('User').logout(function() {
            // user is logged out
            window.location.reload();
        });
    },

    onLoggedIn: function(userRecord) {
        var me = this;

        // keep the record data
        this.active_user = userRecord;

        // now that we are logged in the stores can be loaded
        // (if you want a clean separation of concerns, just fire an application event 'logged in',
        // so each controller loads it's own stores)
        this.getStore('Users').load();
        this.getStore('Comments').load();
        this.getStore('Articles').load({
            callback: function() {
                // articles loaded tell everyone (see Articles controller onArticlesLoaded)
                me.application.fireEvent('articlesloaded');
            }
        });
    },

    init: function(application) {
        var me = this;

        // ask server if already logged in
        Bancha.getStub('User').login({}, {
        success: function(result,response) {
            if(result.success) {
                // user is already logged in
                var user = Ext.create('BlogApp.model.User', result.data);
                me.application.fireEvent('loggedin', user);
            } else {
                // force user to log in
                var win = Ext.create('BlogApp.view.LoginWindow', {});
                win.show();
            }
        }
    });

    this.control({
        "loginwindow button[action=login]": {
            click: this.onLoginClick
        },
        "loginwindow textfield": {
            keypress: this.onLoginEnter
        },
        "tool[action=logout]": {
            click: this.onLogoutClick
        }
    });

    application.on({
        loggedin: {
            fn: this.onLoggedIn,
            scope: this
        }
    });
    }

});
