/*
 * File: app/controller/Articles.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.controller.Articles', {
    extend: 'Ext.app.Controller',
    alias: 'controller.articles',

    refs: [
        {
            ref: 'articlesList',
            selector: 'articleslist'
        },
        {
            ref: 'articleReader',
            selector: 'articlereader'
        },
        {
            ref: 'articlePanel',
            selector: '#articlePanel'
        }
    ],

    onArticleListSelectionChange: function(model, selected, eOpts) {
        // make an application wide event
        this.application.fireEvent('articlechanged',selected[0]);
    },

    onArticleChanged: function(record) {
        /**
        * refresh the single article view
        */
        var me = this,
            view = this.getArticleReader();

        // update the content
        view.tpl.overwrite(view.el, record.data);

        // update the title
        this.getArticlePanel().setTitle(record.get('title'));
    },

    onArticlesLoaded: function() {
        // as default select the first articles list element
        var firstRecord = this.getStore('Articles').getAt(0);
        this.getArticlesList().getSelectionModel().select(firstRecord);

        // this other views will be informed by the triggered application event 'articlechanged';
    },

    onLoggedIn: function(userRecord) {
        /**
        * Only show the article edit and delete to admins
        *
        * Normally I would dynamically render the action items in for the admin view,
        * but since promoting the ActionColumn to a own class breaks it (Designer bug!?)
        * we just remove it for non-admins
        */
        if(userRecord.get('role') === 'admin') {
            return;
        }

        var grid = this.getArticlesList(),
            headerCt = grid.headerCt,
            column = headerCt.getComponent('adminactioncolumn');
        headerCt.remove(column);
        grid.getView().refresh();
    },

    init: function(application) {
        this.control({
            "articleslist": {
                selectionchange: this.onArticleListSelectionChange
            }
        });

        application.on({
            articlechanged: {
                fn: this.onArticleChanged,
                scope: this
            },
            articlesloaded: {
                fn: this.onArticlesLoaded,
                scope: this
            },
            loggedin: {
                fn: this.onLoggedIn,
                scope: this
            }
        });
    }

});
