/*
 * File: app/controller/Articles.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('BlogApp.controller.Articles', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'list',
            selector: 'articleslist'
        },
        {
            ref: 'articleView',
            selector: 'articleview'
        }
    ],

    init: function() {
        this.control({
            "articleslist": {
                selectionchange: this.onArticleListSelectionChange
            }
        });

        this.application.on({
            articlechanged: {
                fn: this.onArticleChanged
            }
        });
    },

    onArticleListSelectionChange: function(tablepanel, selections, options) {
        // make an application wide event
        this.application.fireEvent('articlechanged',selections[0]);
    },

    onArticleChanged: function(record) {
        // refresh the single article view
        var view = Ext.ComponentQuery.query('articleview')[0];
        // this.getArticleView(); should work a well, but there's a problem with references

        view.tpl.overwrite(view.el, record.data);


        // update the title
        Ext.ComponentQuery.query('#articlePanel')[0].setTitle(record.get('title'));
    }

});