/*
 * File: app/controller/Comments.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('BlogApp.controller.Comments', {
    extend: 'Ext.app.Controller',

    init: function() {
        this.control({
        });

        this.application.on({
            articlechanged: {
                fn: this.onArticleChangeD1
            }
        });
    },

    onArticleChangeD1: function(record) {
        // refresh the comments
        this.getCommentsStore().filter('article_id',record.get('id'));
        console.info('refreshing');
    }

});