/*
 * File: js/app/controller/Login.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('BlogApp.controller.Login', {
    extend: 'Ext.app.Controller',

    stores: [
        'Users'
    ],
    refs: [
        {
            ref: 'loginWindow',
            selector: 'loginwindow'
        },
        {
            ref: 'loginForm',
            selector: 'loginWindow formpanel'
        }
    ],

    init: function() {
        this.control({
            "button": {
                click: this.onLogin
            }
        });

        // force login
        var win = Ext.create('BlogApp.view.LoginWindow', {});
        win.show();
    },

    onLogin: function(button, e, options) {
        // log the user in
        var me = this, // keep reference to controller and window through scope
        win = this.getLoginWindow(), 
        values = win.items.items[0].getForm().getValues();

        // login through the banchaRemotable method UsersController->login
        Bancha.getStubsNamespace().User.login(values, function(result,response) {

            if(Ext.isObject(result) && result.id) {

                // we got a record back, so we are logged in
                win.hide();

                // keep the record data
                me.active_user = Ext.create('Bancha.model.User',result);

                // now that we are logged in the stores can be loaded
                // (if you want a clean separation of concerns, just fire an application event 'logged in',
                // so each controller loads it's own stores)
                me.getUsersStore().load();
                me.getStore('Comments').load();
                me.getStore('Articles').load({
                    callback: function() {
                        // articles loaded tell everyone (see Articles controller onArticlesLoaded)
                        me.application.fireEvent('articlesloaded');
                    }
                });

            } else {

                // force login again

                if(result && result.success===false) {
                    Ext.Msg.alert('Login Failed!', 'Username and password don\'t match!');
                } else {
                    Ext.Msg.alert('Warning!', 'Authentication server is unreachable or returned with an error');
                }
            }
        }); 
    }

});