/*
 * File: js/app/view/CommentsList.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('BlogApp.view.CommentsList', {
    extend: 'BlogApp.view.ui.CommentsList',
    alias: 'widget.commentslist',

    initComponent: function() {
        var me = this;
        
        // overwrite template (it's not possible to define memeber function in Ext Designer)
        this.tpl = new Ext.XTemplate(
            '<tpl for="."><div class="comment">{comment}<span class="comment-meta">{[this.getAuthorName(values.user_id)]}, {created}</span></div></tpl>',
            {
                getAuthorName: function(id) {
                	// get the users store
                	var store = Ext.StoreMgr.get('Users');
                	
                	// if the record doesn't exists
                	if(!store || !store.getById(id)) {
                    	return 'undefined';
                	}

                	// return the author's name
                	return store.getById(id).get('name');
                }
            }
        );
        
        me.callParent(arguments);
    }

});