/*
 * File: app/view/CommentsList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.CommentsList', {
    extend: 'Ext.view.View',
    alias: 'widget.commentslist',

    requires: [
        'BlogApp.view.CommentsListViewModel',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'commentslist'
    },
    tpl: Ext.create('Ext.XTemplate', 
        '<tpl for=".">',
        '    <div class="comment">{comment}',
        '        <span class="comment-meta">{[this.getAuthorName(values.user_id)]}{[this.getDate(values.created)]}</span>',
        '    </div>',
        '</tpl>',
        {
            getAuthorName: function(id) {
                // get the users store
                var store = Ext.StoreMgr.get('Users');

                // if the record doesn't exists
                if(!store || !store.getById(id)) {
                    return 'undefined';
                }

                // return the author's name
                return store.getById(id).get('name');
            },
            getDate: function(date) {
                if(date) {
                    return ', '+Ext.Date.format(date, "Y-m-d");
                }
                return '';
            }
        }
    ),
    emptyText: '<br /><i>There are no comments for this article, write the first:</i>',
    itemSelector: 'div',
    store: 'Comments'

});