/*
 * File: app/view/CommentForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.CommentForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.commentform',

    requires: [
        'BlogApp.view.CommentFormViewModel',
        'Ext.form.FieldSet',
        'Ext.form.field.Hidden',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'commentform'
    },
    cls: '',
    bodyCls: [
        'comments-form',
        'x-panel-body-default'
    ],
    bodyPadding: 10,
    frameHeader: false,
    api: {
        submit: 'Bancha.RemoteStubs.Comment.submit'
    },

    items: [
        {
            xtype: 'fieldset',
            title: 'Add a comment',
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: '',
                    name: 'article_id'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: '',
                    name: 'comment',
                    growAppend: '-'
                },
                {
                    xtype: 'toolbar',
                    style: {
                        'margin-bottom': '10px'
                    },
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            action: 'submitComment',
                            cls: 'comment-submit',
                            text: 'submit'
                        }
                    ]
                }
            ]
        }
    ]

});