/*
 * File: app/view/CommentsList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.CommentsList', {
    extend: 'Ext.view.View',
    alias: 'widget.commentslist',

    html: 'loading...',
    emptyText: 'There are no comments for this article, write the first:',
    itemSelector: 'div',
    store: 'Comments',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: Ext.create('Ext.XTemplate', 
                '<tpl for=".">',
                '    <div class="comment">{comment}',
                '        <span class="comment-meta">{[this.getAuthorName(values.user_id)]}{[this.getDate(values.created)]}</span>',
                '    </div>',
                '</tpl>',
                {
                    getAuthorName: function(id) {
                        // get the users store
                        var store = Ext.StoreMgr.get('Users');

                        // if the record doesn't exists
                        if(!store || !store.getById(id)) {
                            return 'undefined';
                        }

                        // return the author's name
                        return store.getById(id).get('name');
                    },
                    getDate: function(date) {
                        if(date) {
                            return ', '+Ext.Date.format(date, "Y-m-d");
                        }
                        return '';
                    }
                }
            )
        });

        me.callParent(arguments);
    }

});