/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginwindow',

    height: 342,
    width: 530,
    resizable: false,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'Login',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: '20 30 0 30',
                    frameHeader: false,
                    title: '',
                    paramsAsHash: true,
                    waitTitle: 'Logging in...',
                    items: [
                        {
                            xtype: 'component',
                            html: [
                                '<h2>Hello to the Sencha Architect example.</h2>',
                                '<p>',
                                'This example has three different authorization levels.',
                                '<br>',
                                'Log in with username and password "martin" to just read the ',
                                'articles and comments. Login as "joe" to also delete comments, ',
                                'and as "roland" you can delete the whole article additionally. ',
                                '<br/><br/>',
                                'Also read more about ',
                                '<a href="http://banchaproject.org/using-sencha-architect-2.html" style="color: black;">',
                                'how to use Sencha Architect</a>. I hope you like it, now log in to play around:',
                                '</p>'
                            ]
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Username',
                            name: 'username',
                            allowBlank: false,
                            enableKeyEvents: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Password',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            enableKeyEvents: true
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                padding: '0 20 20 0',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    action: 'login',
                                    padding: '2 10 2 10',
                                    text: 'login'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});