/*
 * File: app/view/ManageCommentsWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.ManageCommentsWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.managecommentswindows',

    requires: [
        'Ext.grid.plugin.CellEditing'
    ],

    height: 500,
    width: 800,
    layout: {
        type: 'fit'
    },
    title: 'Manage Comments',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    width: 27,
                    store: 'Comments',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'comment',
                            menuDisabled: true,
                            text: 'comment',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            width: 130,
                            dataIndex: 'created',
                            menuDisabled: true,
                            text: 'Created',
                            format: 'Y-m-d H:i'
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 27,
                            menuDisabled: true,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e) {
                                        var store = view.getStore(),
                                            rec = store.getAt(rowIndex);

                                        // this is normally a job for the controller, but to keep the example simple we do it here
                                        store.remove(rec);
                                    },
                                    altText: 'delete',
                                    icon: 'img/icons/delete.png',
                                    tooltip: 'delete'
                                }
                            ]
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {

                        })
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});