/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'BlogApp.view.ArticleList',
        'BlogApp.view.ArticleReader',
        'BlogApp.view.CommentsPanel',
        'Ext.grid.Panel',
        'Ext.panel.Tool',
        'Ext.layout.container.Border'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'articleslist',
                    width: 250,
                    region: 'west',
                    split: true
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'articlePanel',
                    title: 'Article Name',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'articlereader',
                            padding: 10,
                            style: {
                                background: 'white'
                            },
                            flex: 1
                        },
                        {
                            xtype: 'commentspanel',
                            flex: 1
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            action: 'logout',
                            tooltip: 'logout',
                            type: 'minus'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});