/*
 * File: app/view/ui/ArticlesList.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.ui.ArticlesList', {
    extend: 'Ext.grid.Panel',

    title: 'Articles',
    store: 'Articles',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    flex: 2,
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 50,
                    defaultWidth: 50,
                    dataIndex: 'date',
                    flex: 1,
                    text: 'Author'
                },
                {
                    xtype: 'actioncolumn',
                    items: [
                        {
                            icon: 'http://sampleproject.banchaproject.org/img/icons/delete.png',
                            iconCls: '',
                            tooltip: 'Delete Article'
                        }
                    ]
                }
            ],
            viewConfig: {

            }
        });

        me.callParent(arguments);
    }

});