/*
 * File: app/view/ui/CommentsView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BlogApp.view.ui.CommentsView', {
    extend: 'Ext.view.View',

    itemSelector: 'div',
    store: 'Comments',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: [
                '<tpl for="."><div>Comment{comment}<span class="comment-author">{author},{created}</span></div></tpl>'
            ]
        });

        me.callParent(arguments);
    }

});